# -*- coding: utf-8 -*-
"""River_Pollution_Problem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIxVKV4Wo_PLu5Qdblnp9GU1pxcAnb12
"""

from scipy.optimize import minimize

# Objective functions
def f1(x):
    return 4.07 + 2.27 * x[0]

def f2(x):
    return 2.60 + 0.03 * x[0] + 0.02 * x[1] + (0.01 / (1.39 - x[0]**2)) + (0.30 / (1.39 - x[1]**2))

def f3(x):
    return 8.21 - (0.71 / (1.09 - x[0]**2))

def f4(x):
    return 0.96 - (0.96 / (1.09 - x[1]**2))


# Constraint functions
def constraint1(x):
    return x[0] - 0.3

def constraint2(x):
    return x[1] - 0.3

def constraint3(x):
    return 1.0 - x[0]

def constraint4(x):
    return 1.0 - x[1]


# Additional criterion functions for constraints
def f5(x):
    return x[0] - 0.3

def f6(x):
    return x[1] - 0.3

def f7(x):
    return -x[0] + 1.0

def f8(x):
    return -x[1] + 1.0


# Initial guess
x0 = [0.5, 0.5]

# Constraints
cons = [{'type': 'ineq', 'fun': constraint1},
        {'type': 'ineq', 'fun': constraint2},
        {'type': 'ineq', 'fun': constraint3},
        {'type': 'ineq', 'fun': constraint4},
        {'type': 'ineq', 'fun': f5},
        {'type': 'ineq', 'fun': f6},
        {'type': 'ineq', 'fun': f7},
        {'type': 'ineq', 'fun': f8}]

# Reference point
reference_point = [0, 0, 0, 0]

# Weighted sum method for converting maximization to minimization
def weighted_sum(x, ref_point):
    return -(0.25 * (f1(x) - ref_point[0]) + 0.25 * (f2(x) - ref_point[1]) + 0.25 * (f3(x) - ref_point[2]) + 0.25 * (f4(x) - ref_point[3]))


for iteration in range(4):
    result = minimize(weighted_sum, x0, args=(reference_point,), constraints=cons)

    reference_point = [f1(result.x), f2(result.x), f3(result.x), f4(result.x)]
    x0 = result.x

    print("Iteration", iteration+1)
    print("Optimal solution:")
    print("f1 =", reference_point[0])
    print("f2 =", reference_point[1])
    print("f3 =", reference_point[2])
    print("f4 =", reference_point[3])
    print("x1 =", result.x[0])
    print("x2 =", result.x[1])
    print()